#!/bin/bash

# Gerar string aleatória para uso no nome do arquivo de backup
random=$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 5)

# Obter data e hora atual para uso no nome do arquivo de backup
dato=$(date "+%d-%m-%Y_%Hh-%Mm-%Ss")

# Caminho absoluto para o diretório de backup
backup_dir="/root/backupAuto"

# Criar diretório de backup se não existir
mkdir -p "$backup_dir" && echo "Diretório de backup criado com sucesso"

# Adicionar tarefa cron se ainda não estiver configurada
if ! crontab -l | grep -q "0 */5 * * * backmod"; then
    (crontab -l 2>/dev/null; echo "0 */5 * * * backmod") | crontab - && echo "Tarefa cron adicionada com sucesso"
fi

# Copiar arquivos para o diretório de backup
if cp /root/paineldtunnel/prisma/database.db /root/paineldtunnel/.env /root/paineldtunnel/painelbackup; then
    echo "Arquivos copiados com sucesso"
else
    echo "Erro ao copiar arquivos"
    exit 1
fi

# Compactar o diretório de backup
if zip -r "/root/backupAuto/painelbackup-$dato-$random.zip" /root/paineldtunnel/painelbackup; then
    echo "Backup compactado com sucesso"
else
    echo "Erro ao compactar backup"
    exit 1
fi

# Remover o diretório de backup temporário
rm -rf /root/paineldtunnel/painelbackup && echo "Diretório temporário removido com sucesso"
