#!/bin/bash

# Generar cadena aleatoria para uso en el nombre del archivo de respaldo
random=$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 5)

# Obtener fecha y hora actual para uso en el nombre del archivo de respaldo
dato=$(date "+%d-%m-%Y_%Hh-%Mm-%Ss")

# Ruta absoluta para el directorio de respaldo
backup_dir="/root/backupAuto"

# Crear directorio de respaldo si no existe
mkdir -p "$backup_dir" && echo "Directorio de respaldo creado con éxito"

# Agregar tarea cron si aún no está configurada
if ! crontab -l | grep -q "0 */5 * * * backmod"; then
    (crontab -l 2>/dev/null; echo "0 */5 * * * backmod") | crontab - && echo "Tarea cron agregada con éxito"
fi

# Copiar archivos al directorio de respaldo
if cp /root/paineldtunnel/prisma/database.db /root/paineldtunnel/.env /root/paineldtunnel/painelbackup; then
    echo "Archivos copiados con éxito"
else
    echo "Error al copiar archivos"
    exit 1
fi

# Comprimir el directorio de respaldo
if zip -r "/root/backupAuto/painelbackup-$dato-$random.zip" /root/paineldtunnel/painelbackup; then
    echo "Respaldo comprimido con éxito"
else
    echo "Error al comprimir el respaldo"
    exit 1
fi

# Eliminar el directorio de respaldo temporal
rm -rf /root/paineldtunnel/painelbackup && echo "Directorio temporal eliminado con éxito"