#!/bin/bash

do_backup() {
  clear
  echo "Fazendo backup..."
  cd /root/paineldtunnel
  #rm -r painelbackup > /dev/null
  #mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "painelbackup.zip salvo em /root"
  echo
  exit 0
}

toggle_auto_backup() {
  clear
  read -p "DESEA ACTIVAR AUTO BACKUP? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Ativando...."
    backmod
    echo
    echo "Backup de 5 en 5 horas activo!"
    exit 0
  }
  menudt
}

remove_panel() {
  clear
  read -p "DESEA REMOVER EL PANEL? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Removiendo..."
    poff
    rm /bin/pon /bin/poff /bin/menudt /bin/backmod
    rm -r /root/paineldtunnel
    echo "Removido exitosamente!"
    exit 0
  }
  menudt
}

restore_backup() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Archivo painelbackup.zip no encontrado en /root"
    sleep 4
    menudt
  }
  read -p "DESEA RESTAURAR EL BACKUP? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /root/paineldtunnel
    rm prisma/database.db
    rm .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db ../paineldtunnel/prisma
    mv .env ../paineldtunnel
    cd /root
    rm -r painelbackup
    pon
    echo
    echo "Backup restaurado exitosamente!"
    exit 0
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Volviendo al menú"
    sleep 2
    menudt
  }
  menudt
}
#[[ ! -e /root/paineldtunnel/src/index.ts ]] && exit 0
menudt() {
  clear
  echo -e "\033[1;34m╔═════════════════════════════╗\033[0m"
  echo -e "\033[1;34m║\033[1;41m\033[1;32m  MENU PANEL WEBCONT VIP    \033[0m\033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╣\033[0m" 
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m01\033[1;36m] \033[1;32m• \033[1;31mHACER BACKUP          \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m02\033[1;36m] \033[1;32m• \033[1;31mRESTAURAR BACKUP      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m03\033[1;36m] \033[1;32m• \033[1;31mREINICIAR PANEL      \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m04\033[1;36m] \033[1;32m• \033[1;31mACTIVAR AUTO BACKUP    \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m05\033[1;36m] \033[1;32m• \033[1;31mREMOVER PANEL        \033[1;34m║"
  echo -e "\033[1;34m║\033[1;36m[\033[1;32m00\033[1;36m] \033[1;32m• \033[1;31mSALIR                  \033[1;34m║"
  echo -e "\033[1;34m╠═════════════════════════════╝\033[0m"
  echo -ne "\033[1;34m╚➤ \033[1;31mENTRAR UNA OPCIÓN \033[1;33m : "; 
  read resp
  case $resp in
    1) 
    do_backup 
    sleep 3
    menudt
    ;;
    2) 
    restore_backup 
    sleep 3
    menudt
    ;;
    3) 
    clear
    echo "Reiniciando..."
    pon
    echo "Reiniciado exitosamente!"
    sleep 3
    menudt
    ;;
    4) 
    toggle_auto_backup 
    sleep 3
    menudt
    ;;
    5) 
    remove_panel 
    ;;
    0) 
    echo "Saliendo..."
    exit 0 
    ;;
    *) 
    echo "Opcion invalida!"
    sleep 3
    clear
    menudt
  esac
}
menudt
